import { ReactNode } from "react"; // Import ReactNode for type safety
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./_components/Header";
import { AuthProvider } from "./(context)/AuthContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "ContentAI form builder",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <AuthProvider>
      <html lang="en" data-theme="light">
        <body className={inter.className}>
          <Header />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}